version: '3.8'

services:
  postgres:
    image: postgres:13.4
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
  keycloak:
    build:
      context: ./
      dockerfile: ./keycloak/Dockerfile
    command: start --import-realm --hostname localhost --hostname-strict-https false --http-enabled true --http-port 8888
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8888:8888
  mastersofjava:
    build:
      context: ./
      dockerfile: ./mastersofjava/Dockerfile
    depends_on:
      - keycloak
    volumes:
      - mastersofjava:/data
    ports:
      - 8080:8080

volumes:
  postgres:
  mastersofjava:
