version: '3.8'

services:
  postgres:
    image: postgres:13.4
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
  keycloak:
    build:
      context: ./
      dockerfile: ./keycloak/Dockerfile
    depends_on:
      - postgres
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
    ports:
      - 8081:8080
  mastersofjava:
    build:
      context: ./
      dockerfile: ./mastersofjava/Dockerfile
    depends_on:
      - keycloak
    volumes:
      - mastersofjava:/data
    ports:
      - 8080:8080

volumes:
  postgres:
  mastersofjava:
