moj:
  server:
    mode: single
    data-directory: /data
    languages:
      java-versions:
        - version: 10
          name: Java 10
          compiler: /opt/java/10/bin/javac
          runtime: /opt/java/10/bin/java
        - version: 11
          name: Java 11
          compiler: /opt/java/11/bin/javac
          runtime: /opt/java/11/bin/java
        - version: 17
          name: Java 17
          compiler: /opt/java/openjdk/bin/javac
          runtime: /opt/java/openjdk/bin/java
    limits:
      compile-timeout: PT30S
      compile-output-limits:
        max-feedback-lines: 1000
        max-chars: 100000
        max-line-len: 1000
        line-truncated-message: "...{truncated}"
        output-trunc-message: "...{output truncated}"
        timeout-message: "...{terminated: compile time expired}"
      test-timeout: PT30S
      test-output-limits:
        max-feedback-lines: 1000
        max-chars: 100000
        max-line-len: 1000
        line-truncated-message: "...{truncated}"
        output-trunc-message: "...{output truncated}"
        timeout-message: "...{terminated: test time expired}"
    runtime:
      game-threads: 10
    competition:
      success-bonus: 400

spring:
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:${moj.server.data-directory}/db/mastersofjava;db_close_on_exit=false
#    url: jdbc:h2:mem:moj;db_close_on_exit=false
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  thymeleaf:
    mode: HTML
  flyway:
    enabled: true
    baseline-on-migrate: true
  web:
    resources:
      static-locations: classpath:/bootstrap/sounds/,classpath:/static/
  artemis:
    embedded:
      enabled: true
      queues: compile_request,compile_response,test_request,test_response,submit_request,submit_response
    mode: embedded
    broker-url: vm://0
    user: admin
    password: admin
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: moj
            authorization-grant-type: authorization_code
            scope: openid,roles,email,profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/moj
            user-name-attribute: preferred_username
server:
  forward-headers-strategy: native

logging:
  level:
    nl.moj.server: debug
    org.keycloak: error
    "org.apache.activemq.audit.base": error
    "org.apache.activemq.audit.message": error
    "org.apache.catalina.loader.WebappClassLoaderBase": error
